### ISSUE TITLE
Getting AttributeError: 'Namespace' object has no attribute 'realign' error

### ISSUE THREAD

**Issue by max1c** [foerstner-lab/READemption#29]
I installed all dependencies with conda. 

$ reademption align -p 4 --poly_a_clipping -f READemption_analysis
Traceback (most recent call last):
  File "/apps/reademption/1.0.0/bin/reademption", line 315, in <module>
    main()
  File "/apps/reademption/1.0.0/bin/reademption", line 22, in main
    args.func(controller)
  File "/apps/reademption/1.0.0/bin/reademption", line 288, in align_reads
    controller.align_reads()
  File "/apps/reademption/1.0.0/lib/python3.8/site-packages/reademptionlib/controller.py", line 83, in align_reads
    if not self._args.realign:
AttributeError: 'Namespace' object has no attribute 'realign'

**Comment by Tillsa** [comment]
Hello,
Thank you for reporting the bug and sorry for your inconvenience. I fixed the error and released version 1.0.1 
Please install version 1.0.1 and you should be able to run the example analysis without errors.
Best regards,
Till

**Comment by max1c** [comment]
Thanks for the update. It looks like it's working now.

**Comment by Tillsa** [comment]
Great!
