### ISSUE TITLE
Error running gene_quanti

### ISSUE THREAD

**Issue by jina-leemon** [foerstner-lab/READemption#39]
Hello!

I ran alignment and coverage, and while running gene_quanti I encountered this error:

```
jil143@dsmlp-jupyter-jil143:~/teams/CSE185_SP22_A00/group13$ reademption gene_quanti -p 4 --features CDS,tRNA,rRNA -f READemption_pa01
Traceback (most recent call last):
  File "/home/jil143/.local/bin/reademption", line 315, in <module>
    main()
  File "/home/jil143/.local/bin/reademption", line 22, in main
    args.func(controller)
  File "/home/jil143/.local/bin/reademption", line 296, in run_gene_wise_quantification
    controller.quantify_gene_wise()
  File "/home/jil143/.local/lib/python3.9/site-packages/reademptionlib/controller.py", line 827, in quantify_gene_wise
    self._check_job_completeness(jobs)
  File "/home/jil143/.local/lib/python3.9/site-packages/reademptionlib/controller.py", line 782, in _check_job_completeness
    raise (job.exception())
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

Do you know anything about this?

Thank you!

**Comment by Tillsa** [comment]
Hello,
Thank you for your message! Can you please provide the version number of READemption? You can find that out by typing:

$ reademption --version

How did you install reademption?

Best wishes,

Till

**Comment by jina-leemon** [comment]
Hello,

I used pip install reademption and the version is 1.0.5!

**Comment by Tillsa** [comment]
I assume this error happens because of some changes in the library that we use to run parallel tasks (https://docs.python.org/3/library/concurrent.futures.html). We are currently working on a new version of READemption, that solves this error. However, it will only be released in a couple of days. If you you can not wait for the release of the new version, you could switch to the dev branch of READemption and rerun the analysis (note that the syntax changed, you can see an example via --help after each subcommand)
