### ISSUE TITLE
coverage FileNotFoundError (read_alignments_final.json)

### ISSUE THREAD

**Issue by gcabebe** [foerstner-lab/READemption#42]
Hello,

I was able to use the create command to generate folders for a new analysis, and added the reference sequence and annotation files in their respective folders. Below is the folder structure I have so far:

![image](https://user-images.githubusercontent.com/76535363/179887726-229c79f8-d971-4fb7-bd59-c61e25dbc330.png)

This is the line I've been running:
```
reademption coverage -f TestAnalysis
```

And this is the error that keeps showing:
```
Traceback (most recent call last):
  File "/home/gcabebe/anaconda3/envs/reademption/bin/reademption", line 716, in <module>
    main()
  File "/home/gcabebe/anaconda3/envs/reademption/bin/reademption", line 22, in main
    args.func(controller)
  File "/home/gcabebe/anaconda3/envs/reademption/bin/reademption", line 692, in create_coverage_files
    controller.create_coverage_files()
  File "/home/gcabebe/anaconda3/envs/reademption/lib/python3.9/site-packages/reademptionlib/controller.py", line 540, in create_coverage_files
    raw_stat_data_reader.read(
  File "/home/gcabebe/anaconda3/envs/reademption/lib/python3.9/site-packages/reademptionlib/rawstatdata.py", line 22, in read
    with open(input_file) as input_fh:
FileNotFoundError: [Errno 2] No such file or directory: 'TestAnalysis/output/align/reports_and_stats/stats_data_json/read_alignments_final.json'
```

Where is the "read_alignments_final.json" file supposed to come from?

Also to my knowledge, segemehl is properly installed and its directory is added to my ```$PATH``` via .bashrc file.

Thank you!

**Comment by Tillsa** [comment]
Hello Gabrielle Cabebe,

You need to run the alignment with the command 'align' prior to any other subcommand. In your case you have fastq files, so please add the flag --fastq to the command.

Best wishes,

Till Sauerwein

**Comment by gcabebe** [comment]
Thank you! I was referencing documentation from a different program step-by-step and completely missed that step 😅
