### ISSUE TITLE
[Bug] File not found in coverage subcommand

### ISSUE THREAD

**Issue by elhossary** [foerstner-lab/READemption#51]
In Version 2.0.3 I get file not found error when trying to generate the coverage while passing no fragment argument.
It tries to find the alignment stats JSON file for the fragments, but basically I passed ```--no_fragment_building``` when I aligned the reads, so there are actually no fragments stats.

```
reademption coverage --project_path ${READEMPTION_FOLDER} --paired_end --no_fragments --unique_only
Traceback (most recent call last):
  File "/usr/local/bin/reademption", line 716, in <module>
    main()
  File "/usr/local/bin/reademption", line 22, in main
    args.func(controller)
  File "/usr/local/bin/reademption", line 692, in create_coverage_files
    controller.create_coverage_files()
  File "/usr/local/lib/python3.10/dist-packages/reademptionlib/controller.py", line 540, in create_coverage_files
    raw_stat_data_reader.read(
  File "/usr/local/lib/python3.10/dist-packages/reademptionlib/rawstatdata.py", line 22, in read
    with open(input_file) as input_fh:

FileNotFoundError: [Errno 2] No such file or directory: 'READemption_analysis/output/align/reports_and_stats/stats_data_json/fragment_alignments_final.json
```

**Comment by Tillsa** [comment]
Thanks for reporting this Bug. It's fixed in version 2.0.4
